### ISSUE TITLE
Errore dopo docker compose

### ISSUE THREAD

**Issue by archistico** [MineraleYT/pi2w-docker#1]
Ho eseguito tutti i passaggi nell'ordine ma quando lancio il comando:
`
docker compose up -d
`

mi da questo errore
`
unable to get image 'pihole/pihole:latest': permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.47/images/pihole/pihole:latest/json": dial unix /var/run/docker.sock: connect: permission denied
`

Quale potrebbe essere il motivo?

**Comment by archistico** [comment]
Prima di lanciare il comando mi sono loggata su portainer sulla porta 9000, creare utente e password
E poi ho lanciato
`docker stop portainer`  
`docker start portainer`  


Ma quando lancio il compose mi da questo errore:
`docker compose up -d`   
...  
`no matching manifest for linux/arm/v8 in the manifest list entries`

**Comment by archistico** [comment]
trovato il motivo, nel docker compose l'immagine da utilizzare è:
`linuxserver/mariadb:alpine`

```
---
services:
  # Web server
  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d

  # Database
  mariadb:
    image: linuxserver/mariadb:alpine
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  # Database management
  phpmyadmin:
    image: phpmyadmin
    platform: linux/arm64
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - mariadb

  # Automatic container updates
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
    restart: unless-stopped

volumes:
  mariadb:
```
